FROM selenium/standalone-chrome as runtime

USER root
RUN  apt-get update \
  && apt-get install -y libunwind8 \
  && rm -rf /var/lib/apt/lists/*

# Install .NET Core
RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Version 2.2.4 -Runtime dotnet

# Install chromedriver for Selenium
RUN curl https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -o /usr/local/bin/chromedriver
RUN chmod +x /usr/local/bin/chromedriver

# Install Chrome
#RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

USER seluser

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build

WORKDIR /app

# copy the proj and restore packages
COPY *.csproj .
RUN dotnet restore

# copy and publish app and libraries
WORKDIR /app
COPY . .
RUN dotnet publish -c Release -o out

FROM runtime
WORKDIR /app
COPY --from=build /app/out ./
# set the entrypoint
ENTRYPOINT ["dotnet", "GCDownload.dll"]